insert into student_entity value(null,'Cyrus Huff',true);
insert into student_entity value(null,'Raymond Shepard',true);
insert into student_entity value(null,'Hayley Marks',true);
insert into student_entity value(null,'Salvatore Calderon',true);
insert into student_entity value(null,'Braiden Robertson',true);
insert into student_entity value(null,'Megan Knight',true);
insert into student_entity value(null,'Maryjane Ryan',true);
insert into student_entity value(null,'Bridget Mcmillan',true);
insert into student_entity value(null,'Marisa Lynn',true);
insert into student_entity value(null,'Sadie Pollard',true);
insert into student_entity value(null,'Jeffery Solis',true);
insert into student_entity value(null,'Cornelius Fuentes',true);
insert into student_entity value(null,'Presley Larsen',true);
insert into student_entity value(null,'Annabel Rowland',true);
insert into student_entity value(null,'Alisson Davenport',true);
insert into student_entity value(null,'Brynn Lucero',true);
insert into student_entity value(null,'Beau Fritz',true);
insert into student_entity value(null,'Tristen Henderson',true);
insert into student_entity value(null,'Damon Decker',true);
insert into student_entity value(null,'Jett Young',true);
insert into student_entity value(null,'Marlene Holt',true);
insert into student_entity value(null,'Emelia Graves',true);
insert into student_entity value(null,'Sebastian Mejia',true);
insert into student_entity value(null,'Maryjane Walton',true);
insert into student_entity value(null,'Lawson Chung',true);
insert into student_entity value(null,'Areli Molina',true);
insert into student_entity value(null,'Giana Rojas',true);
insert into student_entity value(null,'Nickolas Buck',true);
insert into student_entity value(null,'Vanessa Anthony',true);
insert into student_entity value(null,'Leland Savage',true);
insert into student_entity value(null,'Memphis Garrison',true);
insert into student_entity value(null,'Randy Sanders',true);
insert into student_entity value(null,'Nora Hanson',true);
insert into student_entity value(null,'Maribel Jennings',true);
insert into student_entity value(null,'Amani English',true);
insert into student_entity value(null,'Walker Spence',true);
insert into student_entity value(null,'Uriel Li',true);
insert into student_entity value(null,'Krystal Spears',true);
insert into student_entity value(null,'Adan Mclean',true);
insert into student_entity value(null,'Travis Jacobson',true);
insert into student_entity value(null,'Diana Anthony',true);
insert into student_entity value(null,'Nevaeh Barnes',true);
insert into student_entity value(null,'Justine Berg',true);
insert into student_entity value(null,'Harley Ferguson',true);
insert into student_entity value(null,'Laila Bender',true);
insert into student_entity value(null,'Cristina Doyle',true);
insert into student_entity value(null,'Jordyn Carrillo',true);
insert into student_entity value(null,'Kelton Mccarthy',true);
insert into student_entity value(null,'Leonel Howe',true);
insert into student_entity value(null,'Jamiya Hayden',true);

insert into course_entity value(null,'Science Education',true);
insert into course_entity value(null,'Sound and Music Computing',true);
insert into course_entity value(null,'Linguistic Anthropology',true);
insert into course_entity value(null,'Military Psychology',true);
insert into course_entity value(null,'Earthquake Engineering',true);
insert into course_entity value(null,'Calligraphy',true);
insert into course_entity value(null,'Literary Journalism',true);
insert into course_entity value(null,'Natural Product Chemistry',true);
insert into course_entity value(null,'Educational Leadership',true);
insert into course_entity value(null,'Relativity',true);
insert into course_entity value(null,'Mathematical Economics',true);
insert into course_entity value(null,'Behavioural Genetics',true);
insert into course_entity value(null,'Biological Anthropology',true);
insert into course_entity value(null,'Lexicology',true);
insert into course_entity value(null,'Socioeconomics',true);
insert into course_entity value(null,'Forensic Anthropology',true);
insert into course_entity value(null,'Philosophy of Science',true);
insert into course_entity value(null,'Chemistry Education',true);
insert into course_entity value(null,'European Archaeology',true);
insert into course_entity value(null,'Neuroscience',true);
insert into course_entity value(null,'Condensed Matter Physics',true);
insert into course_entity value(null,'Sociology of Human Consciousness',true);
insert into course_entity value(null,'Fiction Creative Writing',true);
insert into course_entity value(null,'Exercise Physiology',true);
insert into course_entity value(null,'Wireless Computing',true);
insert into course_entity value(null,'Industrial and Labor Relations',true);
insert into course_entity value(null,'Arabic',true);
insert into course_entity value(null,'Journalism',true);
insert into course_entity value(null,'Korean History',true);
insert into course_entity value(null,'Combinatorial Mathematics',true);
insert into course_entity value(null,'Animal Care and Conservation',true);
insert into course_entity value(null,'Sociology of Sport',true);
insert into course_entity value(null,'Magnetohydrodynamics',true);
insert into course_entity value(null,'Philosophy of Pain',true);
insert into course_entity value(null,'Interstellar Medium',true);
insert into course_entity value(null,'Paleoclimatology',true);
insert into course_entity value(null,'Religious Studies',true);
insert into course_entity value(null,'Urban Geography',true);
insert into course_entity value(null,'Cultural Sociology',true);
insert into course_entity value(null,'Medical Physics',true);
insert into course_entity value(null,'Group Psychology',true);
insert into course_entity value(null,'Behavioral Geography',true);
insert into course_entity value(null,'Polymer Physics',true);
insert into course_entity value(null,'Surveying',true);
insert into course_entity value(null,'Alternative Medicine',true);
insert into course_entity value(null,'Military Medicine',true);
insert into course_entity value(null,'Microbiology',true);
insert into course_entity value(null,'Anthropology of Religion',true);
insert into course_entity value(null,'Landscape Design',true);
insert into course_entity value(null,'Anthrozoology ',true);
